### ISSUE TITLE
function ucfirst() not working for multibyte chars

### ISSUE THREAD

**Issue by OKhomiakova** [OKhomiakova/web2-php#2]
Hello @zovube!
Nice try on accomplishing 2nd task! However, are you aware of the fact that the function **ucfirst()**, you are using in your solutin, does not work properly w/ Russian characters (as they are multibyte)?
Please, look into this issue!
I am hoping for your prompt responce. Good luck and have fun! ;)

**Comment by Zovube** [comment]
Hello @OKhomiakova !
Thanks for notifying. My bad, i didn't test my solution enough. Seems like the way you fixed this in your solution is quite good, i would approve this!
Good job!)
